// NextJS imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Clerk imports
import { ClerkProvider } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";

// NextUI imports
import { NextUIProvider } from "@nextui-org/react";

// Styles imports
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Global Developers Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link
          rel="stylesheet"
          href="https://stijndv.com/fonts/Eudoxus-Sans.css"
        />
        <link rel="preconnect" href="https://stijndv.com" />
      </head>
      <body className={inter.className}>
        <ClerkProvider localization={esES}>
          <NextUIProvider>{children}</NextUIProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
